name = str(input('Digite seu nome completo: '))
print('Seu nome em maiúsculas é {}'.format(name.upper()))
print('Seu nome em minúsculas é ' + name.lower())
print('Seu nome tem ao todo {} letras'.format(len(name) - name.count(' ')))
print('Seu primeiro nome é {} e tem {} letras'.format(name.split()[0], len(name.split()[0])))